baseURL = 'https://benhur.me/'
languageCode = 'en-us'
title = 'Benhur Senabathi'
theme = 'PaperMod'

params:
    homeInfoParams:
        Title: Hi, I'm Ben! 
        Content: A product designer at frog