baseURL = 'https://benhur.me/'
languageCode = 'en-us'
title = 'Benhur Senabathi'
theme = 'PaperMod'

  [params]
  [params.homeInfoParams]
  Title = "thoughts & blocks"
  Content = "Welcome to thoughts & blocks where you can read about automations, workflows, astronomy, design.


  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/benhursenabathi/"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/im_benhur"

  [[params.socialIcons]]
  name = "medium"
  url = "https://imbenhur.medium.com/"